Repository googleapis/nodejs-service-directory, pull requests merged in 2020-05, with the labels that each got.

#39 chore: update npm scripts and synth.py
  package.json
  synth.py
Labels: automerge, cla: yes

#40 fix: regenerated unit tests
  synth.metadata
  test/gapic_lookup_service_v1beta1.ts
  test/gapic_registration_service_v1beta1.ts
Labels: automerge, cla: yes

#43 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#45 docs: add samples to CHANGELOG
  README.md
  linkinator.config.json
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none
