Repository googleapis/nodejs-service-directory, pull requests merged in 2020-07, with the labels that each got.

#56 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#57 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#60 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#62 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#63 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#64 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#65 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#66 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#67 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#69 build: config for new reference docs
  .kokoro/release/docs-devsite.cfg
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial
