Repository googleapis/nodejs-service-directory, pull requests merged in 2020-11, with the labels that each got.

#87 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: servicedirectory, automerge, cla: yes, context: full

#88 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1beta1/lookup_service_client.ts
  src/v1beta1/registration_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: servicedirectory, automerge, cla: yes

#94 fix: only fallback if fetch exists on window
  protos/protos.json
  src/v1beta1/lookup_service_client.ts
  src/v1beta1/registration_service_client.ts
  synth.metadata
Labels: api: servicedirectory, cla: yes, context: none

#98 docs: fix typo in README
  README.md
  synth.metadata
Labels: api: servicedirectory, cla: yes, context: none
